title: Mats Julian Olsen
email: mats [at] plysjbyen.net
description: > # this means to ignore newlines until "baseurl:"
    Hi, my name is Mats.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mewwts
github_username:  mewwts

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
